<a href="https://colab.research.google.com/github/crown3633/TaeHun/blob/master/%EC%97%B4%EC%9C%A0%EC%B2%B4%EA%B3%B5%ED%95%99%EC%8B%A4%ED%97%98_2016201278_HW03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
y=int(input("구구단 몇단을 보시겠습니까?"))
A=np.full((9,1),y)
B=(np.arange(1,10)).reshape((9,1))
print(np.hstack([A,B,B*y]))

구구단 몇단을 보시겠습니까?5
[[ 5  1  5]
 [ 5  2 10]
 [ 5  3 15]
 [ 5  4 20]
 [ 5  5 25]
 [ 5  6 30]
 [ 5  7 35]
 [ 5  8 40]
 [ 5  9 45]]
